self-host-postgresql:
    name: Self-Hosted
    alt: Self-Hosted PostgreSQL
    url: https://www.postgresql.org/
    icon: /assets/images/logos/postgresql.png
self-host-mysql:
    name: Self-Hosted
    alt: Self-Hosted MySQL
    url: https://www.mysql.com
    icon: /assets/images/logos/mysql.png
self-host-mariadb:
    name: Self-Hosted
    alt: Self-Hosted MariaDB
    url: https://www.mariadb.com
    icon: /assets/images/logos/mariadb.png
self-host-msad:
    name: On-Premise
    alt: On-Premise Active Directory
    url: https://www.microsoft.com/en-us/windows-server
    icon: /assets/images/logos/activedirectory.png
azure-ad-msad:
    name: Azure AD
    alt: Azure AD
    url: https://azure.microsoft.com/en-us/services/active-directory/
    icon: /assets/images/logos/azure.png
azure-ad-ds-msad:
    name: Azure AD Domain Services
    alt: Azure AD Domain Services
    url: https://azure.microsoft.com/en-us/services/active-directory-ds/
    icon: /assets/images/logos/azureadds.png
self-host-mssql:
    name: Self-Hosted
    alt: Self-Hosted Microsoft SQL Server
    url: https://www.microsoft.com/en-us/sql-server
    icon: /assets/images/logos/mssql.png

