self-host-postgresql:
    name: Self-Hosted
    alt: Self-Hosted PostgreSQL
    url: https://www.postgresql.org/
    icon: /assets/images/logos/postgresql.png
self-host-mysql:
    name: Self-Hosted
    alt: Self-Hosted MySQL
    url: https://www.mysql.com
    icon: /assets/images/logos/mysql.png
self-host-mariadb:
    name: Self-Hosted
    alt: Self-Hosted MariaDB
    url: https://www.mariadb.com
    icon: /assets/images/logos/mariadb.png
